### ISSUE TITLE
播放喜马拉雅专辑出错

### ISSUE THREAD

**Issue by adslyear** [hex-ci/geak-audio#1]
感谢提供，测试使用

node xmly.js 220714
正在下载喜马拉雅专辑...
下载完成！
(node:7020) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at main (D:\geakaudio\xmly.js:39:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by adslyear** [comment]
谢谢！

node xmly.js 220714
D:\geakaudio\xmly.js:7
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<'
[90m    at wrapSafe (internal/modules/cjs/loader.js:1001:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1049:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:950:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m

**Comment by adslyear** [comment]
v14.18.1

**Comment by adslyear** [comment]
应该是的，重新下载提示正常了，谢谢
